### ISSUE TITLE
Fullscreen button of JWVrVideoView does not work properly

### ISSUE THREAD

**Issue by thanhbinh84** [jwplayer/jwplayer-android-best-practice-apps#11] opened 2017-05-10 09:32 UTC
Steps to reproduce: 
- Run 360-video-sample app in portrait mode 
- Press fullscreen button on control bar 
- Rotate phone to landscape 
- Press fullscreen button on control bar again
Screen record: https://drive.google.com/open?id=0B5vdcUhTdl8eZWwyTmF3YXZ4NlU

Current result: 
- The player still plays in landscape mode with paddings in the top and bottom. 

Expected result: 
- The player plays in portrait mode

The current JWVideoView and the youtube app works like as expected behavior, so I think it is right suggestion.

**Comment by RikHeijdens** [comment] 2017-05-10 14:14
This is intended behavior for the JWVrVideoView.
If you want the player to behave similar like YouTube, or the default fullscreen behavior of the JWPlayerView then you can call [`Activity.setRequestedOrientation`](https://developer.android.com/reference/android/app/Activity.html#setRequestedOrientation(int)) upon exiting fullscreen.

**Comment by thanhbinh84** [comment] 2017-05-11 03:47
I did try with Activity.setRequestedOrientation() but it will lock screen to one orientation causing auto rotate disabled, the onConfigurationChanged() will be never called. 
Is it possible to support fullscreen toggle using both ways: pressing on the fullscreen button and rotating phone? 
It doesn't make sense that Youtube, JWPlayerView on Android and JWVrVideoView on iOS share the same behavior except JWVrVideoView on Android, does it?

**Comment by RikHeijdens** [comment] 2017-05-11 07:16
It is certainly possible to rotate the activity/player view when your phone is rotated - we just don't do it by default in the JWVrVideoView for Android.

One approach you could take is register an [OrientationEventListener](https://developer.android.com/reference/android/view/OrientationEventListener.html)  and then listen for OrientationChange events, and then based on some threshold rotate the screen. This is similar to how the JWPlayerView handles orientation changes internally.

**Comment by thanhbinh84** [comment] 2017-05-12 14:35
Thanks @RikHeijdens for the suggestion. You are right, I thought onConfigurationChanged() is the only way to detect screen change. :D 
I attached workable class here, hope it useful or someone points out some bugs. :D 
[VideoActivity.txt](https://github.com/jwplayer/jwplayer-android-best-practice-apps/files/997002/VideoActivity.txt)

**Comment by RikHeijdens** [comment] 2017-05-12 15:16
I'm glad you managed to get it to work.

I'm closing this issue as this is intended behavior.

**Closed by RikHeijdens** 2017-05-12 15:16 UTC

**Comment by mrithun-cgvak** [comment] 2018-05-09 10:07
Hi I am getting the error always while running 360 video sample app as android.view.InflateException: Binary XML file line #10: Binary XML file line #10: Error inflating class com.longtailvideo.jwplayer.vr.JWVrVideoView
                                                     at android.view.LayoutInflater.inflate.
Can anyone help me to resolve this issue.
